import { NextResponse } from 'next/server';

// 1. Tag Detection Logic (Simulated Vision AI)
// In production, this data is dynamically generated by sending the image to OpenAI/Google Vision.
// Each tag is assigned an inherent "Weight" (how valuable/complex it is) and a "Confidence" score (0.0 - 1.0).
const MOCK_AI_TAGS_POOL = [
  { name: 'cyberpunk', weight: 6.5, confidence: 0.85 },
  { name: 'neon', weight: 4.2, confidence: 0.91 },
  { name: 'architecture', weight: 3.5, confidence: 0.94 },
  { name: 'nighttime', weight: 2.0, confidence: 0.98 },
  { name: 'rain', weight: 5.5, confidence: 0.72 },
  { name: 'urban', weight: 3.0, confidence: 0.95 },
  { name: 'sunset', weight: 4.5, confidence: 0.88 },
  { name: 'golden hour', weight: 5.0, confidence: 0.75 },
  { name: 'sky', weight: 1.0, confidence: 0.99 },
  { name: 'symmetry', weight: 7.0, confidence: 0.65 },
  { name: 'brutalism', weight: 6.0, confidence: 0.82 },
  { name: 'nature', weight: 2.0, confidence: 0.97 },
];

export async function POST(request: Request) {
  try {
    const formData = await request.formData();
    const file = formData.get('image');

    if (!file) {
      return NextResponse.json({ error: 'No image uploaded' }, { status: 400 });
    }

    // 2. Point Calculation Formula
    // The core equation: Points = Weight * Confidence * Rarity Bonus
    // We calculate a Uniqueness Bonus (1.0 to 1.5) based on how rare the combination of tags is.
    const rarityBonus = 1.0 + (Math.random() * 0.5); 
    
    const numTags = Math.floor(Math.random() * 5) + 4; // 4 to 8 tags
    const shuffledPool = [...MOCK_AI_TAGS_POOL].sort(() => 0.5 - Math.random());
    const selectedTags = shuffledPool.slice(0, numTags);
    
    let rawTotalPoints = 0;
    
    const processedTags = selectedTags.map(tag => {
      // Execute the math for every single tag
      const points = tag.weight * tag.confidence * rarityBonus;
      
      // Add to the cumulative total
      rawTotalPoints += points;
      
      return {
        tag_text: `#${tag.name}`,
        weight: tag.weight,
        confidence: tag.confidence,
        points_contributed: Number(points.toFixed(2)),
        is_high_value: tag.weight >= 4.0
      };
    });

    // 3. Total Score Calculation
    // We take the raw sum and apply a scaling factor to fit a beautiful 0-100 visual score.
    const finalScore = Math.min(100, Number((rawTotalPoints * 3.5).toFixed(1)));

    // Generate an actionable Pro-Tip for the user based on their score
    const proTip = finalScore > 80 
      ? "💡 PASS Tip: Incredible lighting! High-contrast scenes always score massive points."
      : "💡 PASS Tip: Try framing more complex subjects to increase your base tag weight!";

    return NextResponse.json({
      success: true,
      timestamp: new Date().toISOString(),
      total_points_earned: finalScore,
      tags: processedTags,
      analysis_breakdown: {
        raw_points: rawTotalPoints.toFixed(2),
        rarity_multiplier: rarityBonus.toFixed(2),
        tags_detected: processedTags.length
      },
      pro_tip: proTip
    });

  } catch (error) {
    console.error('PASS Engine Error:', error);
    return NextResponse.json({ error: 'Failed to process image' }, { status: 500 });
  }
}
